services:
  ollama:
    profiles:
      - ollama
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  arsa:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_SLIM: ${USE_SLIM-true}
    container_name: arsa
    volumes:
      - arsa:/app/backend/data
    ports:
      - ${ARSA_PORT-3000}:8080
    environment:
      ENABLE_OLLAMA_API: ${ENABLE_OLLAMA_API-false}
      ENABLE_OPENAI_API: ${ENABLE_OPENAI_API-true}
      OPENAI_API_BASE_URL: ${OPENAI_API_BASE_URL-https://api.openai.com/v1}
      OPENAI_API_KEY: ${OPENAI_API_KEY-}
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY-}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  arsa: {}
